[package]
name = "neuroflow"
version = "0.1.0"
authors = ["Mikhail Kravets <michkravets@gmail.com>"]
exclude = ["examples/*"]

[dependencies]
time = "0.1"
rand = "0.3"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "^0.9"