[package]
name = "neuroflow"
version = "0.1.0"

description = "The neural network library implemented in Rust"
repository = "https://github.com/MikhailKravets/NeuroFlow"
readme = "README.md"
keywords = ["neural", "networks", "deep", "learning", "backpropagation"]
categories = ["algorithms", "science"]
license = "MIT"

authors = ["Mikhail Kravets <michkravets@gmail.com>"]
exclude = ["examples/*", "tests/*"]

[badges]
travis-ci = { repository = "MikhailKravets/NeuroFlow", branch = "master" }
codecov = { repository = "MikhailKravets/NeuroFlow", branch = "master", service = "github" }

[dependencies]
time = "0.1"
rand = "0.3"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "^0.9"